### PR TITLE
Add upload directory and download directory

### PR DESCRIPTION
**Pull request by shuyuImpossible**
TFTP server can download from a directory while upload to another directory.

### CODE REVIEW

**Comment by shuyuImpossible** [comment]
@altugbakan  please review, i am not familiar with rust, there may be some foolish coding error.

**Comment by altugbakan** [comment]
Hey! Thanks for the work, I changed Upload to Receive and Download to Send to fix potential confusions about who is uploading and who is downloading, now send is the directory that the server sends from, and receive is the directory to receive new files.

**Review by altugbakan — APPROVED** [review]
LGTM!

**Comment by stappersg** [comment]
```text
On Sat, Nov 04, 2023 at 04:42:19AM -0700, Altu?? Bakan wrote:
> @altugbakan pushed 1 commit.
> 
> 1eb7363f98ebe85f313cc90d1bda7ab817bc157a  Rename upload and download to receive and send
> 

Sadly, very sadly, got that commit melted with the original commits.

It should have been in a separate commit.


Please prevent in future "constructions" like

    Co-authored-by: y1shu <yu.shu@nokia-sbell.com>
    Co-authored-by: Altu?? Bakan <mail@alt.ug>
```

**Pull request merged**
