### PR TITLE
Update error logs to include filename and client info

### PR DESCRIPTION
**Pull request by mayurikini**

### CODE REVIEW

**Review by stappersg — APPROVED** [review]
Looks good  (and FWIW the commit message is very terse)

**Review by altugbakan — APPROVED** [review]

**Comment by mayurikini** [comment]
@altugbakan can we get new version release?

**Comment by mayurikini** [comment]
@stappersg could you release new version?

**Comment by stappersg** [comment]
On Fri, Jan 10, 2025 at 01:04:01PM -0800, Mayuri Kini wrote:
> @stappersg could you release new version? 

Please elaborate.

**Comment by altugbakan** [comment]
> @altugbakan can we get new version release?

I will do it today

**Pull request merged**
